create_groups_new_view
kirinkubinagai/chat-space pull request #11
Opened 2016-11-21 11:38 UTC by kirinkubinagai

#WHAT
グループのnew画面作成
#WHY
グループ機能実装のため

2016-11-21 11:51 UTC, kirinkubinagai commented
![2016-11-21 19 41 13](https://cloud.githubusercontent.com/assets/20741515/20481775/3df859f6-b02c-11e6-8284-1b4c9d9b30dc.png)

2016-11-21 12:14 UTC, hand12 reviewed
いくつかコメントしたのでご確認ください。

2016-11-21 12:14 UTC, hand12 commented on README.md
>    |name|string|not null|
本番と合わせなくていいですよ！

2016-11-21 12:14 UTC, hand12 commented on app/controllers/chat_groups_controller.rb
> +  end
createのときは条件分岐も書きましょう！
成功した時と失敗した時です。

2016-11-21 12:14 UTC, hand12 commented on app/controllers/chat_groups_controller.rb
> +  end
このアクションまだ実装していないので、必要になったら書くようにしましょう！

2016-11-21 12:14 UTC, hand12 commented on app/views/chat_groups/new.html.haml
> +        = f.label :グループ名, class: "chat-group-form__label"
このままではlabelの本来の機能を使えていません。
labelタグが一体何をしているのかを調べてみてください！

2016-11-21 12:17 UTC, kirinkubinagai commented on app/controllers/chat_groups_controller.rb
> +  end
わかりました！

2016-11-21 12:17 UTC, kirinkubinagai commented on app/controllers/chat_groups_controller.rb
> +  end
わかりました

2016-11-21 12:57 UTC, kirinkubinagai commented on app/views/chat_groups/new.html.haml
> +        = f.label :グループ名, class: "chat-group-form__label"
わかりました調べてみます

2016-11-21 13:04 UTC, kirinkubinagai commented on app/views/chat_groups/new.html.haml
> +        = f.label :グループ名, class: "chat-group-form__label"
labelがあれば子要素にチェックボックスがあった時など、インラインなど当てられる範囲が広がるということですね。
ここからhtmlの構造ごと変えるのはちょっと嫌なのでpタグに置き換えます。すいません

2016-11-22 02:34 UTC, kirinkubinagai commented
![2016-11-22 11 24 47](https://cloud.githubusercontent.com/assets/20741515/20508814/9eea6de6-b0a7-11e6-8d3e-8dcdc5e7fe79.png)

2016-11-22 02:34 UTC, kirinkubinagai commented
![2016-11-22 11 24 30](https://cloud.githubusercontent.com/assets/20741515/20508822/a664710c-b0a7-11e6-9bb2-0f900f9d537d.png)

2016-11-22 02:35 UTC, kirinkubinagai commented
すいません画像貼り忘れてました。

2016-11-22 02:41 UTC, mizuki-h commented on README.md
> +##  messages
余計なスペースが入っているので修正をお願いします。

2016-11-22 02:41 UTC, mizuki-h commented on app/views/chat_groups/edit.html.haml
> +  = form_for @chat_group, class: "edit_chat_group",id:"edit_chat_group" do |f|
細かいですが、カンマの後ろにスペースが空いているところと空いていないところがバラバラなので、
今回は、カンマの後ろに１つスペースを空けるで統一してここから書いていきましょう！

``` = form_for @chat_group, class: "edit_chat_group", id:"edit_chat_group" do |f|  ```
他のところも同様に修正してみてください！

2016-11-22 02:41 UTC, mizuki-h commented on app/controllers/untitled.haml
> +  end
後ろに空行を追加してください！
自動的に一行空行を追加してくれるパッケージがあると思うので、そちら調べていただいて導入して見てもいいかなと思います！

2016-11-22 05:29 UTC, hc0208 requested changes

2016-11-22 05:29 UTC, hc070208 commented on app/controllers/chat_groups_controller.rb
> +    @chat_group=ChatGroup.find(params[:id])
@chat_group=ChatGroup.find(params[:id]) が2度出てきているのでbefore_actionなどでprivat以下にメソッドとして1つにまとめてあげるといいと思います。

2016-11-22 05:49 UTC, hc070208 commented
LGTM

2016-11-22 05:50 UTC, merged